# Generated by Django 3.0.3 on 2020-02-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('priority', models.SmallIntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
