# Generated by Django 3.0.3 on 2020-02-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDS', '0003_auto_20200227_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='message',
            field=models.TextField(),
        ),
    ]
