# Generated by Django 3.0.3 on 2020-03-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDS', '0004_auto_20200227_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='danger',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
